pe_help/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from pe_help.settings import *
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pe_help.views.home', name='home'),
    # url(r'^pe_help/', include('pe_help.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^cj/', include('cahier_journal.url'),
    url(r'^cj/(?P<object>\w+)/(?P<id>\d+)/$', 'cahier_journal.views.show'),
    url(r'^cj/journee/(?P<annee>\d+)/(?P<mois>\d+)/(?P<jour>\d+)/$', 'cahier_journal.views.journee'),
    url(r'^cj/objectif/$', 'cahier_journal.views.objectif'),
    url(r'^cj/getjson/(?P<object>\w+)/(?P<id_parent>\d+)/$', 'cahier_journal.views.getjson'),
    url(r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': MEDIA_ROOT}),
)

cahier_journal/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.forms import ModelForm
from cahier_journal.widgets import ColorPickerWidget
from datetime import timedelta
from django import forms


class ColorField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 10
        super(ColorField, self).__init__(*args, **kwargs)

    def formfield(self, **kwargs):
        kwargs['widget'] = ColorPickerWidget
        return super(ColorField, self).formfield(**kwargs)


class Domaine(models.Model):
    NIVEAUX = (
                   ('Maternelle', (
                                   ('ps', 'PS'),
                                   ('ms', 'MS'),
                                   ('gs', 'GS'),
                                  )
                   ),
                   ('Cycle 2', (
                                ('cp', 'CP'),
                                ('ce1', 'CE1'),
                                ('ce2', 'CE2'),
                               )
                   ),
                   ('Cycle 3', (
                                ('cm1', 'CM1'),
                                ('cm2', 'CM2'),
                               )
                   )
                  )
    titre = models.CharField(max_length=250)
    niveau = models.CharField(max_length=50, choices=NIVEAUX, blank=True, null=True)
    couleur = ColorField(blank=True, null=True)
    def __unicode__(self):
        return self.titre


class Competence(models.Model):
    titre = models.CharField(max_length=250)
    domaine = models.ForeignKey(Domaine)
    def __unicode__(self):
        return self.titre
    class Meta:
        verbose_name = 'compétence'


class Objectif(models.Model):
    titre = models.CharField(max_length=250)
    competence = models.ForeignKey(Competence)
    def __unicode__(self):
        return self.titre


class Activite(models.Model):
    titre = models.CharField(max_length=200)
    objectif = models.ManyToManyField(Objectif)
    def __unicode__(self):
        return self.titre
    class Meta:
        verbose_name = 'activité'


class Creneau(models.Model):
    date_debut = models.DateTimeField()
    duree = models.TimeField()
    date_fin = models.DateTimeField(blank=True, null=True)
    activite = models.ForeignKey(Activite, related_name='creneaux')
    groupe = models.CharField(max_length=100, blank=True, null=True)
    bilan = models.TextField(blank=True, null=True)
    def save(self):
        self.date_fin = self.date_debut + timedelta(seconds = self.duree.minute * 60 + self.duree.hour * 3600)
        super(Creneau, self).save()
    def __unicode__(self):
        return self.date_debut.strftime('%d/%m/%y %H:%M')
    class Meta:
        verbose_name = 'créneau'
        verbose_name_plural = 'créneaux'


class DomaineForm(ModelForm):
    class Meta:
        model = Domaine


class CompetenceForm(ModelForm):
    class Meta:
        model = Competence


class ObjectifForm(ModelForm):
    class Meta:
        model = Objectif


class ActiviteForm(ModelForm):
    class Meta:
        model = Activite
        #widgets = { 'objectif': forms.HiddenInput(), }


class CreneauForm(ModelForm):
    class Meta:
        model = Creneau
        exclude = ('date_fin')
        widgets = {'date_debut': forms.DateTimeInput(attrs={'class': 'datetimepicker'}),
                    'duree': forms.TimeInput(attrs={'class': 'timepicker'}),
        }

cahier_journal/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from cahier_journal.models import *
from django.core import serializers

def getjson(request, object, id_parent):
    if object == 'competence':
        liste = Competence.objects.filter(domaine__pk__exact=id_parent)
    if object == 'objectif':
        liste = Objectif.objects.filter(competence__pk__exact=id_parent)
    data = {}
    for i in liste:
        data[i.pk] = i
    return HttpResponse(serializers.serialize("json", liste))

def show(request, object, id):
    if object == 'activite':
        try:
            o = Activite.objects.get(pk=id)
        except Activite.DoesNotExist:
            o = Activite()
        if request.POST:
            form = ActiviteForm(request.POST, instance = o)
            if form.is_valid():
                form.save()
                o = form.instance
        else:
            form = ActiviteForm(instance = o)
        return render(request, 'base_activite.html', {
            'form': form,
            'o': o,
            'object': object,
            'domaines': Domaine.objects.all(),
            'competences': Competence.objects.all(),
            'objectifs': Objectif.objects.all(),
        })
    elif object == 'creneau':
        try:
            o = Creneau.objects.get(pk=id)
        except Creneau.DoesNotExist:
            o = Creneau()
        if request.POST:
            form = CreneauForm(request.POST, instance = o)
        else:
            form = CreneauForm(instance = o)
    elif object == 'competence':
        try:
            o = Competence.objects.get(pk=id)
        except Competence.DoesNotExist:
            o = Competence()
        if request.POST:
            form = CompetenceForm(request.POST, instance = o)
        else:
            form = CompetenceForm(instance = o)
    elif object == 'domaine':
        try:
            o = Domaine.objects.get(pk=id)
        except Domaine.DoesNotExist:
            o = Domaine()
        if request.POST:
            form = DomaineForm(request.POST, instance = o)
        else:
            form = DomaineForm(instance = o)
    elif object == 'objectif':
        try:
            o = Objectif.objects.get(pk=id)
        except Objectif.DoesNotExist:
            o = Objectif()
        if request.POST:
            form = ObjectifForm(request.POST, instance = o)
        else:
            form = ObjectifForm(instance = o)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            o = form.instance
        return HttpResponseRedirect(reverse('cahier_journal.views.show', args=(object, o.id)))
    return render(request, 'base_show.html', {
            'form': form,
            'o': o,
            'object': object,
    })


def journee(request, annee, mois, jour):
    creneaux = Creneau.objects.filter(date_debut__startswith='%s-%s-%s' %(annee, mois, jour))
    return render(request, 'base_journee.html', {
            'creneaux': creneaux,
            'annee': annee,
            'mois': mois,
            'jour': jour,
    })


def objectif(request):
    return render(request, 'base_objectif.html', {
            'objectifs': Objectif.objects.all(),
            'domaines': Domaine.objects.all(),
            'competences': Competence.objects.all(),
    })

cahier_journal/templates/base.html
<html>
<head>
<script type="text/javascript" src="{{ MEDIA_URL }}commun/jquery.min.js" ></script>
<script type="text/javascript" src="{{ MEDIA_URL }}commun/js/jquery-ui-1.8.21.custom.min.js"></script>
<link rel="stylesheet" media="screen" type="text/css" title="Design" href="{{ MEDIA_URL }}commun/css/ui-lightness/jquery-ui-1.8.21.custom.css" />
<script>
$(document).ready(function() {
    $('#datepicker').datepicker();
    $('#datepicker').change(function(data) {
        location.replace('/cj/journee/' + $('#datepicker').val().split('/')[2] + '/' + $('#datepicker').val().split('/')[0] + '/' + $('#datepicker').val().split('/')[1] + '/');
    });
});
</script>
{% block head %}{% endblock %}
</head>
<body>
<div id='header'><a href='/cj/journee/'>Journées</a> - <a href='/cj/creneau/'>Scéances</a> - <a href='/cj/domaine/0/'>Domaines</a> - <a href='/cj/competence/0/'>Compétences</a> - <a href = '/cj/objectif/0/'>Objectifs</a> - <a href ='/cj/activite/0/'>Activités</a></div>
{% block content %}{% endblock %}
<div id='footer'><p>Changer de journée : <input id='datepicker' type='text'></p></div>
</body>
</html>

cahier_journal/templates/base_activite.html
{% extends 'base.html' %}

{% block head %}
<script type="text/javascript" src="{{ MEDIA_URL }}commun/jquery.colorPicker.js"></script>
<link rel="stylesheet" media="screen" type="text/css" title="Design" href="{{ MEDIA_URL }}commun/colorPicker.css" />
<script type="text/javascript" src="{{ MEDIA_URL }}commun/update_select.js" ></script>
<script>
var sel = [];
{% if o.pk %}
{% for s in o.objectif.all %}
    sel.push({
        'domaine' : ['{{ s.competence.domaine.titre }}', '{{ s.competence.domaine.pk }}'],
        'competence' : ['{{ s.competence.titre }}', '{{ s.competence.pk }}'],
        'objectif' : ['{{ s.titre }}', '{{ s.pk }}']
    });
{% endfor %}
{% endif %}
function del(sel_id){
    sel.splice(sel_id,1);
    calculeSel();
}

function calculeSel(){
    $('#selection').text('');
    var w = []
    for (s in sel){
        $('#selection').append('<img src="{{ MEDIA_URL }}commun/delete.png" href="#" onClick="del(' + s + ');"> ' + sel[s].domaine[0] + ' - ' + sel[s].competence[0] + ' - ' + sel[s].objectif[0] + '<br>');
        w.push(sel[s].objectif[1]);
    }
    $('#id_objectif').val(w);
}

$(document).ready(function() {
    calculeSel();
    $('#id_objectif').parent().toggle();
    $('select').change(function(data) {
        var s = {
            'domaine' : 'competence',
            'competence' : 'objectif'
            };
        if (this.id in s){
            UpdateSelect(s[this.id], this.value);
        }
    });
    //A AMELIORER
    $('#add').click(function() {
        sel.push({
            'domaine' : [$('#domaine option:selected').text(), $('#domaine option:selected').val()],
            'competence' : [$('#competence option:selected').text(), $('#competence option:selected').val()],
            'objectif' : [$('#objectif option:selected').text(), $('#objectif option:selected').val()]
        });
        calculeSel();
    });
    ////
});
</script>
{% endblock %}

{% block content %}
<h1>{{object|capfirst}}</h1>
<div class='form'>
<form action='/cj/{{ object }}/{% if o.id %}{{o.id}}{% else %}0{% endif %}/' method='post'>
{% csrf_token %}
{{ form.as_p }}
<div id='selection'>
</div>
<select id='domaine'>
<option value='0'></option>
{% for i in domaines %}<option value='{{ i.pk }}'>{{ i }}</option>{% endfor %}
</select>
<select id='competence'>
</select>
<select id='objectif'>
</select>
<input type='button' id='add' value='Ajouter'>
<br><input type='submit' value='Enregistrer !'>
</form>
</div>
{% endblock %}

cahier_journal/templates/base_journee.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="/media/cj/table.css">
{% endblock %}


{% block content %}
<h1>Journée du {{jour}}/{{mois}}/{{annee}}</h1>
{% if creneaux %}
    <table>
        <thead><tr>
             <th>Créneau</th>
             <th>Groupe</th>
             <th>Domaine</th>
             <th>Compétence</th>
             <th>Objectif</th>
             <th>Activité</th>
             <th>Bilan</th>
        </tr></thead>
        <tbody>
    {% for i in creneaux %}
        {% if i.activite.objectif.all|length > 1 %}
            {% for p in i.activite.objectif.all %}
                {% if forloop.first %}
                    <tr>
                        <td rowspan='{{ i.activite.objectif.all|length }}'><a href='/cj/creneau/{{ i.id }}/'>{{ i.date_debut|date:'H:i' }}<br>{{ i.date_fin|date:'H:i' }}</a></td>
                        <td rowspan='{{ i.activite.objectif.all|length }}'>{{ i.groupe }}</td>
                        <td><font color='{{ p.competence.domaine.couleur }}'>{{ p.competence.domaine }}</font></td>
                        <td>{{ p.competence }}</td>
                        <td>{{ p }}</td>
                        <td rowspan='{{ i.activite.objectif.all|length }}'><a href='/cj/activite/{{ i.activite.id }}/'>{{ i.activite.titre }}</a></td>
                        <td rowspan='{{ i.activite.objectif.all|length }}'>{{ i.bilan }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td><font color='{{ p.competence.domaine.couleur }}'>{{ p.competence.domaine }}</font></td>
                        <td>{{ p.competence }}</td>
                        <td>{{ p }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% else %}
            <tr>
                <td><a href='/cj/creneau/{{ i.id }}/'>{{ i.date_debut|date:'H:i' }}<br>{{ i.date_fin|date:'H:i' }}</a></td>
                <td>{{ i.groupe }}</td>
                <td><font color='{{ i.activite.objectif.all.0.competence.domaine.couleur }}'>{{ i.activite.objectif.all.0.competence.domaine }}</font></td>
                <td>{{ i.activite.objectif.all.0.competence }}</td>
                <td>{{ i.activite.objectif.all.0 }}</td>
                <td><a href='/cj/activite/{{ i.activite.id }}/'>{{ i.activite.titre }}</a></td>
                <td>{{ i.bilan }}</td>
            </tr>
        {% endif %}
    {% endfor %}
        </tbody>
    </table>
{% else %}
<p>Il n'y a rien de programmé pour ce jour.</p>
{% endif %}
{% endblock %}

cahier_journal/templates/base_objectif.html
{% extends 'base.html' %}

{% block head %}
<script type="text/javascript" src="{{ MEDIA_URL }}commun/update_select.js" ></script>
<script>
$(document).ready(function() {
    $('select').change(function(data) {
        var s = {
            'domaine' : 'competence',
            'competence' : 'objectif'
            };
        if (this.id in s){
            UpdateSelect(s[this.id], this.value);
        }
    });
});
</script>
{% endblock %}



{% block content %}
<select id='domaine'>
{% for i in domaines %}<option value='{{ i.pk }}'>{{ i }}</option>{% endfor %}
</select>
<select id='competence'>
</select>
<select id='objectif'>
</select>
{% endblock %}

cahier_journal/templates/base_show.html
{% extends 'base.html' %}

{% block head %}
<script type="text/javascript" src="{{ MEDIA_URL }}commun/jquery.colorPicker.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}commun/js/jquery-ui-timepicker-addon.js"></script>
<link rel="stylesheet" media="screen" type="text/css" title="Design" href="{{ MEDIA_URL }}commun/colorPicker.css" />
<link rel="stylesheet" media="screen" type="text/css" title="Design" href="{{ MEDIA_URL }}commun/css/jquery-ui-timepicker-addon.css" />
<script>
$(document).ready(function() {
    $('.datetimepicker').datetimepicker({
        stepMinute: 10,
        hourMin: 8,
        hourMax: 17,
        dateFormat: 'dd/mm/yy',
        timeFormat: 'hh:mm:ss',
    });
    $('.timepicker').timepicker({
        stepMinute: 5,
        timeFormat: 'hh:mm:ss',
    });
});
</script>
{% endblock %}

{% block content %}
<h1>{{object|capfirst}}</h1>
<div class='form'>
<form action='/cj/{{ object }}/{% if o.id %}{{o.id}}{% else %}0{% endif %}/' method='post'>
{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Valider !'>
</form>
</div>
{% endblock %}